services:
  api:
    build:
      context: ./services/api
      dockerfile: Dockerfile
      args:
        - APP_VERSION=${GIT_SHA:-dev}
    env_file:
      - ./services/api/.env.dev
    ports:
      # port host: contenair (:-by default if is not in env)
      - "${API_PORT:-8000}:8000"
    volumes:
      - ./services/api:/app:rw
      - api_data:/data
    restart: unless-stopped

  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
    env_file:
      - ./services/frontend/.env.dev
    ports:
      - "${FRONT_PORT:-5173}:5173"
    depends_on:
      - api
    restart: unless-stopped

volumes:
  api_data: {}
